[package]
name = "cellular_physics"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.17.0-rc.2"
ndshape = "0.3.0"
parking_lot = "0.12.4"
