[package]
name = "cellular_physics"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.17.1"
enum-map = "2.7.3"
ndshape = "0.3.0"
nonmax = "0.5.5"
parking_lot = "0.12.4"
